Controllers/NewsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using AdminPoodle.Data;
using AdminPoodle.Models;
using Microsoft.AspNetCore.Hosting;
using LazZiya.ImageResize; // Bilder
using System.Drawing; // Bilder

namespace AdminPoodle.Controllers
{
    public class NewsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IWebHostEnvironment _hostEnvironment;
        private string wwwRootPath;

        //Bilder
        private int ImageWidth= 640;
        private int ImageHeigth=420;

        public NewsController(ApplicationDbContext context, IWebHostEnvironment hostEnvironment)
        {
            _context = context;
            _hostEnvironment = hostEnvironment;
            wwwRootPath = _hostEnvironment.WebRootPath;
        }

        // GET: News
        public async Task<IActionResult> Index()
        {
              return _context.News != null ? 
                          View(await _context.News.ToListAsync()) :
                          Problem("Entity set 'ApplicationDbContext.News'  is null.");
        }

        // GET: News/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.News == null)
            {
                return NotFound();
            }

            var news = await _context.News
                .FirstOrDefaultAsync(m => m.Id == id);
            if (news == null)
            {
                return NotFound();
            }

            return View(news);
        }

        // GET: News/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: News/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Title,Post,ImageFile, AltText, DateCreated")] News news)
        {
            if (ModelState.IsValid)
            {

                    if (news.ImageFile != null) {

                    //Spara bilder till wwwroot
                    string fileName = Path.GetFileNameWithoutExtension(news.ImageFile.FileName);
                    string extension = Path.GetExtension(news.ImageFile.FileName);

                    //Plockar bort mellanslag i filnam + lägger till timestamp
                    news.ImageName = fileName = fileName.Replace(" ", String.Empty) + DateTime.Now.ToString("yymmssfff") + extension;
                    string path = Path.Combine(wwwRootPath + "/imageupload", fileName);

                    //Lagra Fil
                    using (var fileStream = new FileStream(path, FileMode.Create)) 
                    {
                        await news.ImageFile.CopyToAsync(fileStream);
                    }

                    //Funktion för att ange bildens storlek
                    createImageFile(fileName);

                }
                else {
                    news.ImageName = null;
                }

                _context.Add(news);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(news);
        }



        // GET: News/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.News == null)
            {
                return NotFound();
            }

            var news = await _context.News.FindAsync(id);
            if (news == null)
            {
                return NotFound();
            }
            return View(news);
        }

        // POST: News/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Title,Post,ImageName,AltText,DateCreated")] News news)
        {
            if (id != news.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(news);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!NewsExists(news.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(news);
        }

        // GET: News/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.News == null)
            {
                return NotFound();
            }

            var news = await _context.News
                .FirstOrDefaultAsync(m => m.Id == id);
            if (news == null)
            {
                return NotFound();
            }

            return View(news);
        }

        // POST: News/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.News == null)
            {
                return Problem("Entity set 'ApplicationDbContext.News'  is null.");
            }
            var news = await _context.News.FindAsync(id);
            if (news != null)
            {
                _context.News.Remove(news);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool NewsExists(int id)
        {
          return (_context.News?.Any(e => e.Id == id)).GetValueOrDefault();
        }

        //Funktion för bilder
         
         private void createImageFile(string fileName) {

            using(var img = Image.FromFile(Path.Combine(wwwRootPath + "/imageupload/" , fileName))) {
              
               img.Scale(ImageWidth, ImageHeigth).SaveAs(Path.Combine(wwwRootPath + "/imageupload" + fileName)); 
            } 


         }

    }
}

Controllers/PupController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using AdminPoodle.Data;
using AdminPoodle.Models;
using LazZiya.ImageResize; // Bilder
using System.Drawing; // Bilder

namespace AdminPoodle.Controllers
{
    public class PupController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IWebHostEnvironment _hostEnvironment;
        private string wwwRootPath;

                //Bilder
        private int ImageWidth= 640;
        private int ImageHeigth= 420;


        public PupController(ApplicationDbContext context, IWebHostEnvironment hostEnvironment)
        {
            _context = context;
            _hostEnvironment = hostEnvironment;
            wwwRootPath = _hostEnvironment.WebRootPath;
        }

        // GET: Pup
        public async Task<IActionResult> Index()
        {
              return _context.Pup != null ? 
                          View(await _context.Pup.ToListAsync()) :
                          Problem("Entity set 'ApplicationDbContext.Pup'  is null.");
        }

        // GET: Pup/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Pup == null)
            {
                return NotFound();
            }

            var pup = await _context.Pup
                .FirstOrDefaultAsync(m => m.Id == id);
            if (pup == null)
            {
                return NotFound();
            }

            return View(pup);
        }

        // GET: Pup/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Pup/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Title,Gender,Booked,ImageFile, AltText")] Pup pup)
        {
            if (ModelState.IsValid)
            {

                 if (pup.ImageFile != null) {

                    //Spara bilder till wwwroot
                    string fileName = Path.GetFileNameWithoutExtension(pup.ImageFile.FileName);
                    string extension = Path.GetExtension(pup.ImageFile.FileName);

                    //Plockar bort mellanslag i filnam + lägger till timestamp
                    pup.ImageName = fileName = fileName.Replace(" ", String.Empty) + DateTime.Now.ToString("yymmssfff") + extension;

                    string path = Path.Combine(wwwRootPath + "/imageupload", fileName);

                    //Lagra Fil
                    using (var fileStream = new FileStream(path, FileMode.Create)) 
                    {
                        await pup.ImageFile.CopyToAsync(fileStream);
                    }

                     createImageFile(fileName);

                }
                else {
                    pup.ImageName = null;
                }



                _context.Add(pup);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(pup);
        }

        // GET: Pup/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Pup == null)
            {
                return NotFound();
            }

            var pup = await _context.Pup.FindAsync(id);
            if (pup == null)
            {
                return NotFound();
            }
            return View(pup);
        }

        // POST: Pup/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Title,Gender,Booked, AltText, ImageName")] Pup pup)
        {
            if (id != pup.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(pup);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PupExists(pup.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(pup);
        }

        // GET: Pup/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Pup == null)
            {
                return NotFound();
            }

            var pup = await _context.Pup
                .FirstOrDefaultAsync(m => m.Id == id);
            if (pup == null)
            {
                return NotFound();
            }

            return View(pup);
        }

        // POST: Pup/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Pup == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Pup'  is null.");
            }
            //Inkluderar Buyer för radering
            var pup = await _context.Pup.Include(s => s.Buyer)
            .FirstOrDefaultAsync(m => m.Id == id);
            if (pup != null)
            {
                _context.Pup.Remove(pup);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PupExists(int id)
        {
          return (_context.Pup?.Any(e => e.Id == id)).GetValueOrDefault();
        }


                //Funktion för biler
         
         private void createImageFile(string filename) {

            using(var img = Image.FromFile(Path.Combine(wwwRootPath + "/imageupload/" , filename))) {
              
                img.Scale(ImageWidth, ImageHeigth).SaveAs(Path.Combine(wwwRootPath + "/imageupload" + filename));
            } 


         }
    }
}

Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager

<!DOCTYPE html>
<html lang="sv">
<head>
    <meta charset="utf-8" />
    <link rel="icon" href="~/icons/favico.ico">
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] | Pudelklubben</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/AdminPoodle.styles.css" asp-append-version="true" />
        <link href="https://fonts.googleapis.com/css2?family=Amatic+SC&family=Quicksand:wght@500&display=swap" rel="stylesheet"> 
    <link href="https://fonts.googleapis.com/css2?family=Amatic+SC:wght@700&display=swap" rel="stylesheet">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
             <!--   <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Hem</a> -->
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Hem</a>
                        </li> 
                        @if (SignInManager.IsSignedIn(User))
{
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="News" asp-action="Index">Nyheter</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Pup" asp-action="Index">Valpar</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Interest" asp-action="Index">Intresse</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Buyer" asp-action="Index">Köpare</a>
                        </li> }
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody() <!-- Dynamiskt innehåll -->
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Pudelklubben
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>